### PR TITLE
Add test cases for InterviewSlot

### LINKED ISSUE #61: Additional test cases for Interview Slot
Need additional test cases for some functionality

### PR DESCRIPTION
**Pull request by laughingkid-sg**
Added additional test cases for interview slots to improve code coverage.

Fix #61

### CODE REVIEW

**Review by lchokhoe — APPROVED** [review]
Not sure if it's intentional but should VALID_INTERSHIPSLOT_SHOPEE be VALIDE_INTERNSHIPSLOT_SHOPEE instead? (not sure if you spelt Internship wrongly)

Same comment for VALID_INTERSHIPSLOT_GARENA.

Other then that LGTM, I'll review with approval but won't merge yet.

**Comment by laughingkid-sg** [comment]
Should

> Not sure if it's intentional but should VALID_INTERSHIPSLOT_SHOPEE be VALIDE_INTERNSHIPSLOT_SHOPEE instead? (not sure if you spelt Internship wrongly)
> 
> Same comment for VALID_INTERSHIPSLOT_GARENA.
> 
> Other then that LGTM, I'll review with approval but won't merge yet.

Should be VALID_INTERSHIPSLOT_SHOPEE, following the convention of remaining test cases.

**Comment by laughingkid-sg** [comment]
> Not sure if it's intentional but should VALID_INTERSHIPSLOT_SHOPEE be VALIDE_INTERNSHIPSLOT_SHOPEE instead? (not sure if you spelt Internship wrongly)
> 
> Same comment for VALID_INTERSHIPSLOT_GARENA.
> 
> Other then that LGTM, I'll review with approval but won't merge yet.

Update `VALID_INTERSHIPSLOT_SHOPEE` to `VALID_INTERVIEWSLOT_SHOPEE`

**Review by lchokhoe — APPROVED** [review]
LGTM.

**Pull request merged**
